import { usageError } from '../cli/exit.js';
import type { Profile } from './schema.js';

/**
 * T23 (B8): every built-in as a complete literal object typechecked against
 * `Profile` - `baseline`, `eager-escalation`, `patient`, `no-repair`,
 * `tier1-only`, `strong-only`, `votes3`, `batch1`, `batch2`, `batch3`,
 * `batch5`, `batch8`.
 *
 * Every field is written out on every profile below (not spread from
 * `baseline` with overrides), so a reader never has to mentally apply a diff
 * to see what a profile actually does. The batch family is written out as
 * five separate literals for the same reason, rather than generated by a
 * factory over a single varying field: a reader scanning `batch5` should see
 * every field, not a call site plus a shared template.
 */
export const baseline = {
  name: 'baseline',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const eagerEscalation = {
  name: 'eager-escalation',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 0,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'eager',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const patient = {
  name: 'patient',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 3,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'patient',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 500 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const noRepair = {
  name: 'no-repair',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: false, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const tier1Only = {
  name: 'tier1-only',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 0,
    escalationsPerSlot: 0,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const strongOnly = {
  name: 'strong-only',
  tier1: 'deepseek-ai/DeepSeek-V4-Pro',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 2.0, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 16, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const votes3 = {
  name: 'votes3',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'votes',
  samples: 3,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.7, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const batch1 = {
  name: 'batch1',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const batch2 = {
  name: 'batch2',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 2,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const batch3 = {
  name: 'batch3',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 3,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const batch5 = {
  name: 'batch5',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 5,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

export const batch8 = {
  name: 'batch8',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 8,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 15,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: '1',
} satisfies Profile;

/** Keyed by the CLI-facing / `Profile.name` spelling, e.g. `xw solve --profile eager-escalation`. */
const BUILTINS: Readonly<Record<string, Profile>> = {
  baseline,
  'eager-escalation': eagerEscalation,
  patient,
  'no-repair': noRepair,
  'tier1-only': tier1Only,
  'strong-only': strongOnly,
  votes3,
  batch1,
  batch2,
  batch3,
  batch5,
  batch8,
};

/** A fresh copy each call, so a caller mutating the result never corrupts the shared literal. */
export function getBuiltins(): Record<string, Profile> {
  const out: Record<string, Profile> = {};
  for (const [name, profile] of Object.entries(BUILTINS)) {
    out[name] = { ...profile };
  }
  return out;
}

export function getBuiltin(name: string): Profile {
  const profile = BUILTINS[name];
  if (profile === undefined) {
    throw usageError(
      `unknown built-in profile "${name}"`,
      `known built-ins: ${builtinNames().join(', ')}`,
    );
  }
  return { ...profile };
}

export function builtinNames(): string[] {
  return Object.keys(BUILTINS);
}
