import { usageError } from '../cli/exit.js';
import { PAIRED_PROMPT_VERSION, PROMPT_VERSION } from '../llm/prompts.js';
import type { Profile } from './schema.js';

/**
 * T23 (B8): every built-in as a complete literal object typechecked against
 * `Profile` - `baseline`, `baseline-pv3`, `eager-escalation`, `patient`,
 * `no-repair`, `tier1-only`, `strong-only`, `votes3`, `batch1`, `batch2`,
 * `batch3`, `batch5`, `batch8`.
 *
 * `maxTier2CallsPerPuzzle` is 25 rather than the schema default of 15 (T62):
 * the canonical bench spent the 15 on all-`?` escalations at termination, and
 * once the constrained re-ask fires first the cap has to cover the slots that
 * genuinely reach tier 2 with letters on the board (about 20% of the slots of
 * a 15x15, which is what the algorithms doc's "start at 15" was aiming at).
 * `tier1-only` keeps 0, which is what makes it tier-1 only.
 *
 * Every field is written out on every profile below (not spread from
 * `baseline` with overrides), so a reader never has to mentally apply a diff
 * to see what a profile actually does. The batch family is written out as
 * five separate literals for the same reason, rather than generated by a
 * factory over a single varying field: a reader scanning `batch5` should see
 * every field, not a call site plus a shared template.
 *
 * `promptVersion` is the one exception to "written out as a literal": every
 * ordinary built-in below is `PAIRED_PROMPT_VERSION` from `llm/prompts.ts`,
 * currently `"2"` (T66). It is the profile's copy that reaches the B23 cache
 * key (`candidates/service.ts`) and the inference log, so a bump that changed
 * the prompt bytes here but left these literals behind would serve the old
 * version's cached responses to the new version's prompts. `llm/prompts.ts`
 * is the single owner of both version strings (B49); this module only
 * chooses, per built-in, which of its two exported constants to wire up - it
 * never spells a version number out itself.
 *
 * `baseline-pv3` is the one profile that carries `PROMPT_VERSION` (`"3"`)
 * instead. It exists for a single experiment: version 3 is version 2 with
 * the count-and-drop length self-check removed, and a paired follow-up
 * measurement (72 runs, three repeats each; docs/benches/escalation-policy.md)
 * found version 2 beats version 3 on every accuracy metric, so version 2
 * came back as the default (T66, reverting T65's choice) while version 3
 * stays selectable for anyone who wants to re-run the comparison. It is
 * `baseline` in every other field, so a paired run differs in the prompt
 * bytes and in nothing else.
 */
export const baseline = {
  name: 'baseline',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

/**
 * `baseline` with promptVersion 3 (T66), for the paired measurement described
 * on the doc comment above. Every other field is `baseline`'s.
 */
export const baselinePv3 = {
  name: 'baseline-pv3',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PROMPT_VERSION,
} satisfies Profile;

export const eagerEscalation = {
  name: 'eager-escalation',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 0,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'eager',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const patient = {
  name: 'patient',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 3,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'patient',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 500 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const noRepair = {
  name: 'no-repair',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: false, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const tier1Only = {
  name: 'tier1-only',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 0,
    escalationsPerSlot: 0,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const strongOnly = {
  name: 'strong-only',
  tier1: 'deepseek-ai/DeepSeek-V4-Pro',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 2.0, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 16, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const votes3 = {
  name: 'votes3',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'votes',
  samples: 3,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.7, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const batch1 = {
  name: 'batch1',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 1,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const batch2 = {
  name: 'batch2',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 2,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const batch3 = {
  name: 'batch3',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 3,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const batch5 = {
  name: 'batch5',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 5,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

export const batch8 = {
  name: 'batch8',
  tier1: 'nvidia/Nemotron-3_5-Lightning',
  tier2: 'deepseek-ai/DeepSeek-V4-Pro',
  candidatesPerAsk: 10,
  calibration: 'rank',
  samples: 1,
  batchSize: 8,
  reasksPerSlot: 2,
  sampling: { temperature: 0.2, maxTokens: 512 },
  escalation: {
    policy: 'reask-first',
    clueUnderstoodThreshold: 0.4,
    maxTier2CallsPerPuzzle: 25,
    escalationsPerSlot: 1,
  },
  search: { ordering: 'margin', ldsLimitStart: 0, ldsLimitMax: 3, maxBacktracks: 200 },
  repair: { enabled: true, maxCalls: 30, maxEditDistance: 2 },
  budget: { usd: 0.5, tokens: 2_000_000, wallMs: 900_000 },
  rateLimit: { rpsFraction: 0.9, maxConcurrencyTier1: 8, maxConcurrencyTier2: 16 },
  promptVersion: PAIRED_PROMPT_VERSION,
} satisfies Profile;

/**
 * Keyed by the CLI-facing / `Profile.name` spelling, e.g.
 * `xw solve --profile eager-escalation`.
 *
 * A `Map`, deliberately, not an object literal keyed by name: every lookup
 * below takes a string a user typed (`--profile`, a profile file's
 * `"extends"`, T47's `--profiles`), and `SOME_OBJECT[name]` also resolves
 * `Object.prototype`'s members. On an object literal, `getBuiltin('__proto__')`
 * would answer with `Object.prototype` (cloned to `{}` and typed `Profile`)
 * and `getBuiltin('constructor')`, `getBuiltin('toString')` or
 * `getBuiltin('hasOwnProperty')` would reach a function, which
 * `structuredClone` rejects with a `DataCloneError` - a non-`CliError` that
 * exits 1 with a stack trace instead of the usage error this module promises.
 * A `Map` has no inherited entries, so those names are simply absent, like any
 * other unknown profile name.
 */
const BUILTINS: ReadonlyMap<string, Profile> = new Map<string, Profile>([
  ['baseline', baseline],
  ['baseline-pv3', baselinePv3],
  ['eager-escalation', eagerEscalation],
  ['patient', patient],
  ['no-repair', noRepair],
  ['tier1-only', tier1Only],
  ['strong-only', strongOnly],
  ['votes3', votes3],
  ['batch1', batch1],
  ['batch2', batch2],
  ['batch3', batch3],
  ['batch5', batch5],
  ['batch8', batch8],
]);

/**
 * A deep copy each call, so a caller mutating the result - including a
 * nested group such as `.sampling` or `.budget` - never corrupts the shared
 * module-level literal. A shallow `{ ...profile }` is not enough: the six
 * nested groups (`sampling`, `escalation`, `search`, `repair`, `budget`,
 * `rateLimit`) would still be shared references.
 *
 * The returned record is keyed by the same fixed literal names as `BUILTINS`,
 * so building it by assignment is safe; look a user-supplied name up with
 * `getBuiltin()` rather than by indexing this record, for the reason given on
 * `BUILTINS` above.
 */
export function getBuiltins(): Record<string, Profile> {
  const out: Record<string, Profile> = {};
  for (const [name, profile] of BUILTINS) {
    out[name] = structuredClone(profile);
  }
  return out;
}

export function getBuiltin(name: string): Profile {
  const profile = BUILTINS.get(name);
  if (profile === undefined) {
    throw usageError(
      `unknown built-in profile "${name}"`,
      `known built-ins: ${builtinNames().join(', ')}`,
    );
  }
  return structuredClone(profile);
}

export function builtinNames(): string[] {
  return [...BUILTINS.keys()];
}
