import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { CliError, ExitCode } from '../../../src/cli/exit.js';
import { xwordlyAdapter, type XwordlyAdapterContext } from '../../../src/puzzle/adapters/xwordly.js';
import type { PuzzleWithSolution, Slot } from '../../../src/puzzle/types.js';

function fixtureUrl(name: string): URL {
  return new URL(`../../fixtures/puzzles/${name}`, import.meta.url);
}

/** Raw bytes for every format: the adapter always takes a `Buffer`, text or binary alike. */
function readFixtureBytes(name: string): Buffer {
  return readFileSync(fixtureUrl(name));
}

/**
 * The canonical normalised fixture, minus `schemaVersion` and `fetchedAt`
 * (acceptance item 1) and minus `parsedBy`. `synthetic-5x5.json` and
 * `synthetic-7x7.json` are shared, frozen ground truth for both this task
 * (T24, `@xwordly/xword-parser`) and its sibling T25 (`.xd`, `xd-hand` or
 * `xd-crossword-tools`), so they can only encode one `parsedBy` value -
 * they hold "xd-crossword-tools". Acceptance item 5 pins the value this
 * adapter must actually produce ("@xwordly/xword-parser") separately below,
 * so `parsedBy` is excluded here rather than the two conflicting acceptance
 * items being made to fight over one field. See the PR's deviations note.
 */
function readExpected(name: string): Record<string, unknown> {
  const raw = JSON.parse(readFileSync(fixtureUrl(`${name}.json`), 'utf8')) as Record<string, unknown>;
  const { schemaVersion: _schemaVersion, fetchedAt: _fetchedAt, parsedBy: _parsedBy, ...rest } = raw;
  return rest;
}

/** Reads the solved word for a slot back out of a parsed puzzle's solution grid. */
function wordAt(puzzle: PuzzleWithSolution, slot: Slot): string {
  return slot.cells.map(([row, col]) => puzzle.solution[row]?.[col] ?? '').join('');
}

/** A parsed result with `parsedBy` dropped, to compare against `readExpected`. */
function withoutParsedBy(puzzle: PuzzleWithSolution): Record<string, unknown> {
  const { parsedBy: _parsedBy, ...rest } = puzzle;
  return rest;
}

/**
 * Generator for `test/fixtures/puzzles/synthetic-5x5.puz`, committed here per
 * the T24 baked-in decision ("the .puz fixture is generated by a small
 * committed script inside the test file"). The 'byte-equal to the committed
 * fixture' test below regenerates the file with this function and compares,
 * so the binary on disk can never silently drift from what this comment
 * documents.
 *
 * Section layout this function writes (offsets from the start of the file,
 * matching AcrossLite's `.puz` format and `@xwordly/xword-parser`'s
 * `dist/puz-*.mjs` `readHeader`/`parsePuz`):
 *
 *   0x00  2   global checksum (zeroed - the package reads but never
 *             validates this field, see the top-of-file adapter comment)
 *   0x02 12   magic "ACROSS&DOWN\0"
 *   0x0e  2   CIB checksum (zeroed)
 *   0x10  2   masked low checksum (zeroed)
 *   0x12  2   masked high checksum (zeroed)
 *   0x14  4   version "1.3\0"
 *   0x18  2   reserved1 (zeroed)
 *   0x1a  2   scrambled checksum (zeroed)
 *   0x1c 12   reserved2 (zeroed)
 *   0x28  4   reserved, read but unnamed by the parser (zeroed)
 *   0x2c  1   width (5)
 *   0x2d  1   height (5)
 *   0x2e  2   numClues, little-endian (11)
 *   0x30  2   puzzleType, little-endian (1 = normal)
 *   0x32  2   scrambledTag, little-endian (0 = unscrambled)
 *   0x34 25   solution, row-major, "." marks a block
 *   0x4d 25   player state, row-major, "." at a block, "-" elsewhere
 *   ...       title\0, author\0, copyright\0
 *   ...       one \0-terminated clue string per numbered run, in
 *             CLUES_5X5_SPEC_ORDER below (the file's TRUE spec order:
 *             interleaved by number, across before down at a shared number -
 *             NOT grouped as "all across, then all down"; that grouping is
 *             what the reviewed bug in the adapter used to assume)
 *   ...       notes\0 (empty)
 */
const GRID_5X5 = {
  width: 5,
  height: 5,
  // "." = block, otherwise the uppercase solution letter; matches
  // synthetic-5x5.json's solution grid row-major.
  rows: ['OH.PI', 'RAYON', 'AVOID', 'LOUSE', '.C.EX'],
} as const;

/**
 * Row-major over GRID_5X5's numbered cells, across before down at a shared
 * cell: 1(A,D), 2(D), 3(A,D), 4(D), 5(A), 6(D), 7(A), 8(A), 9(A). This is the
 * order `computeNumbering`'s `runs` produces (T7) and the order a
 * spec-conformant `.puz` stores its clue-string section in.
 */
const CLUES_5X5_SPEC_ORDER: ReadonlyArray<{ id: string; text: string }> = [
  { id: '1A', text: 'Cry of surprise' },
  { id: '1D', text: 'Spoken rather than written' },
  { id: '2D', text: 'Chaos and destruction' },
  { id: '3A', text: 'Greek letter of a famous ratio' },
  { id: '3D', text: 'Calm self-assurance' },
  { id: '4D', text: 'Alphabetical list at the back of a book' },
  { id: '5A', text: 'Synthetic silk-like fabric' },
  { id: '6D', text: 'The person being addressed' },
  { id: '7A', text: 'Steer clear of' },
  { id: '8A', text: 'Small parasitic insect' },
  { id: '9A', text: 'Former partner' },
];

function nullTerminated(text: string): Buffer {
  return Buffer.concat([Buffer.from(text, 'latin1'), Buffer.from([0])]);
}

function le16(n: number): Buffer {
  const buf = Buffer.alloc(2);
  buf.writeUInt16LE(n, 0);
  return buf;
}

function buildSyntheticPuz(): Buffer {
  const { width, height, rows } = GRID_5X5;
  const solution = rows.join('');
  const playerState = rows.map((row) => row.replace(/[^.]/g, '-')).join('');

  const header = Buffer.concat([
    le16(0), // global checksum
    nullTerminated('ACROSS&DOWN'), // magic, 12 bytes incl. terminator
    le16(0), // CIB checksum
    le16(0), // masked low checksum
    le16(0), // masked high checksum
    nullTerminated('1.3'), // version, 4 bytes incl. terminator
    le16(0), // reserved1
    le16(0), // scrambled checksum
    Buffer.alloc(12), // reserved2
    Buffer.alloc(4), // reserved (unnamed by the parser)
    Buffer.from([width]),
    Buffer.from([height]),
    le16(CLUES_5X5_SPEC_ORDER.length),
    le16(1), // puzzleType: normal
    le16(0), // scrambledTag: unscrambled
  ]);

  const body = Buffer.concat([
    Buffer.from(solution, 'latin1'),
    Buffer.from(playerState, 'latin1'),
    nullTerminated('Synthetic five'), // title
    nullTerminated('crossword-agent'), // author
    nullTerminated(''), // copyright
    ...CLUES_5X5_SPEC_ORDER.map((clue) => nullTerminated(clue.text)),
    nullTerminated(''), // notes
  ]);

  return Buffer.concat([header, body]);
}

const FIXTURES: ReadonlyArray<{ file: string; ctx: XwordlyAdapterContext }> = [
  {
    file: 'synthetic-5x5.ipuz',
    ctx: { id: 'synthetic-5x5', source: 'synthetic', origin: 'synthetic-5x5.ipuz', style: 'american' },
  },
  {
    file: 'synthetic-5x5.puz',
    ctx: { id: 'synthetic-5x5', source: 'synthetic', origin: 'synthetic-5x5.puz', style: 'american' },
  },
  {
    file: 'synthetic-5x5.jpz',
    ctx: { id: 'synthetic-5x5', source: 'synthetic', origin: 'synthetic-5x5.jpz', style: 'american' },
  },
  {
    file: 'synthetic-7x7.ipuz',
    ctx: { id: 'synthetic-7x7', source: 'synthetic', origin: 'synthetic-7x7.ipuz', style: 'american' },
  },
];

describe('xwordlyAdapter', () => {
  it('parses synthetic-5x5.ipuz to match the canonical fixture', async () => {
    const result = await xwordlyAdapter.parse(readFixtureBytes('synthetic-5x5.ipuz'), FIXTURES[0]!.ctx);
    expect(withoutParsedBy(result)).toEqual(readExpected('synthetic-5x5'));
  });

  it('parses synthetic-5x5.puz to match the canonical fixture', async () => {
    const result = await xwordlyAdapter.parse(readFixtureBytes('synthetic-5x5.puz'), FIXTURES[1]!.ctx);
    expect(withoutParsedBy(result)).toEqual(readExpected('synthetic-5x5'));
  });

  it('regenerates synthetic-5x5.puz byte-for-byte from buildSyntheticPuz()', () => {
    expect(readFixtureBytes('synthetic-5x5.puz')).toEqual(buildSyntheticPuz());
  });

  it('maps a spec-ordered .puz clue section onto the correct slots (1D, 3A)', async () => {
    // synthetic-5x5.puz's clue-string section is interleaved by number,
    // across before down at a shared number (CLUES_5X5_SPEC_ORDER), which is
    // how a real AcrossLite .puz stores clues and NOT the "all across, then
    // all down" grouping @xwordly/xword-parser's PUZ reader assumes. Regression
    // test for the reviewed bug: 1D and 3A must not pick up each other's (or
    // any other slot's) clue text.
    const result = await xwordlyAdapter.parse(readFixtureBytes('synthetic-5x5.puz'), FIXTURES[1]!.ctx);
    const slot1D = result.slots.find((s) => s.id === '1D');
    const slot3A = result.slots.find((s) => s.id === '3A');
    expect(slot1D?.clue).toBe('Spoken rather than written');
    expect(slot3A?.clue).toBe('Greek letter of a famous ratio');
  });

  it('parses synthetic-5x5.jpz to match the canonical fixture', async () => {
    const result = await xwordlyAdapter.parse(readFixtureBytes('synthetic-5x5.jpz'), FIXTURES[2]!.ctx);
    expect(withoutParsedBy(result)).toEqual(readExpected('synthetic-5x5'));
  });

  it('parses synthetic-7x7.ipuz to match the canonical fixture', async () => {
    const result = await xwordlyAdapter.parse(readFixtureBytes('synthetic-7x7.ipuz'), FIXTURES[3]!.ctx);
    expect(withoutParsedBy(result)).toEqual(readExpected('synthetic-7x7'));
  });

  it('sets parsedBy to "@xwordly/xword-parser" for every format it handles', async () => {
    for (const { file, ctx } of FIXTURES) {
      const result = await xwordlyAdapter.parse(readFixtureBytes(file), ctx);
      expect(result.parsedBy).toBe('@xwordly/xword-parser');
    }
  });

  it('carries the 7x7 multi-word slot enumeration and leaves the clue text unchanged', async () => {
    const result = await xwordlyAdapter.parse(readFixtureBytes('synthetic-7x7.ipuz'), FIXTURES[3]!.ctx);
    const slot = result.slots.find((s) => s.id === '9A');
    expect(slot?.enumeration).toBe('(3,4)');
    expect(slot?.clue).toBe('US city on the Hudson (3,4)');
  });

  it('normalises an accented source letter to plain A-Z (FIANCEE)', async () => {
    const result = await xwordlyAdapter.parse(readFixtureBytes('synthetic-7x7.ipuz'), FIXTURES[3]!.ctx);
    const slot = result.slots.find((s) => s.id === '11A');
    expect(slot).toBeDefined();
    expect(wordAt(result, slot!)).toBe('FIANCEE');
  });

  it('B42: no slot clue contains any slot solution as a substring, across every fixture', async () => {
    for (const { file, ctx } of FIXTURES) {
      const puzzle = await xwordlyAdapter.parse(readFixtureBytes(file), ctx);
      const words = puzzle.slots.map((slot) => wordAt(puzzle, slot).toLowerCase());
      for (const slot of puzzle.slots) {
        const clueLower = slot.clue.toLowerCase();
        for (const word of words) {
          if (word.length === 0) continue;
          expect(clueLower.includes(word), `${file} ${slot.id}: clue "${slot.clue}" leaks "${word}"`).toBe(
            false,
          );
        }
      }
    }
  });

  it('throws a NOT_FOUND CliError naming the first divergent cell on a numbering mismatch', async () => {
    const raw = JSON.parse(readFileSync(fixtureUrl('synthetic-5x5.ipuz'), 'utf8')) as {
      puzzle: unknown[][];
    };
    // r0c0 is numbered 1 in the fixture; force a mismatch against the recomputed numbering.
    raw.puzzle[0]![0] = 99;
    const bytes = Buffer.from(JSON.stringify(raw), 'utf8');

    let caught: unknown;
    try {
      await xwordlyAdapter.parse(bytes, {
        id: 'mismatch',
        source: 'synthetic',
        origin: 'mismatch.ipuz',
      });
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(CliError);
    const cliError = caught as CliError;
    expect(cliError.code).toBe(ExitCode.NOT_FOUND);
    expect(cliError.message).toContain('r0c0');
  });

  it('throws a NOT_FOUND CliError naming the cell on a rebus square', async () => {
    const raw = JSON.parse(readFileSync(fixtureUrl('synthetic-5x5.ipuz'), 'utf8')) as {
      solution: string[][];
    };
    // r1c1 ("A" in RAYON) carries no clue number, so this cannot also trip the
    // numbering-mismatch check above - only the rebus check should fire.
    raw.solution[1]![1] = 'ST';
    const bytes = Buffer.from(JSON.stringify(raw), 'utf8');

    let caught: unknown;
    try {
      await xwordlyAdapter.parse(bytes, { id: 'rebus', source: 'synthetic', origin: 'rebus.ipuz' });
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(CliError);
    const cliError = caught as CliError;
    expect(cliError.code).toBe(ExitCode.NOT_FOUND);
    expect(cliError.message).toContain('r1c1');
  });

  it('rejects a solution letter that is still not A-Z after normalisation', async () => {
    const raw = JSON.parse(readFileSync(fixtureUrl('synthetic-5x5.ipuz'), 'utf8')) as {
      solution: string[][];
    };
    raw.solution[2]![2] = '3';
    const bytes = Buffer.from(JSON.stringify(raw), 'utf8');

    let caught: unknown;
    try {
      await xwordlyAdapter.parse(bytes, { id: 'bad-letter', source: 'synthetic', origin: 'bad-letter.ipuz' });
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(CliError);
    const cliError = caught as CliError;
    expect(cliError.code).toBe(ExitCode.NOT_FOUND);
    expect(cliError.message).toContain('r2c2');
  });

  it('defaults style to "unknown" when the caller does not supply one', async () => {
    const result = await xwordlyAdapter.parse(readFixtureBytes('synthetic-5x5.ipuz'), {
      id: 'synthetic-5x5',
      source: 'synthetic',
      origin: 'synthetic-5x5.ipuz',
    });
    expect(result.style).toBe('unknown');
  });
});
